name: Multi Job CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Run tests
        run: echo "Tests passed"

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Build application
        run: echo "This is the built application" > app.txt

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: application-build
          path: app.txt

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v5
        with:
          name: application-build

      - name: Show artifact
        run: cat app.txt

      - name: Deploy application
        run: echo "Deploy completed"
